export const data1 = [
  {
    account_category: "revenue",
    account_code: "200",
    account_currency: "AUD",
    account_identifier: "e2bacdc6-2006-43c2-a5da-3c0e5f43b452",
    account_status: "ACTIVE",
    value_type: "credit",
    account_name: "Sales",
    account_type: "sales",
    account_type_bank: "",
    system_account: "",
    total_value: 32431.0,
  },
  {
    account_category: "revenue",
    account_code: "200",
    account_currency: "AUD",
    account_identifier: "e2bacdc6-2006-43c2-a5da-3c0e5f43b452",
    account_status: "ACTIVE",
    value_type: "credit",
    account_name: "Sales",
    account_type: "sales",
    account_type_bank: "",
    system_account: "",
    total_value: 324.0,
  },
  {
    account_category: "expense",
    account_code: "200",
    account_currency: "AUD",
    account_identifier: "e2bacdc6-2006-43c2-a5da-3c0e5f43b452",
    account_status: "ACTIVE",
    value_type: "credit",
    account_name: "Sales",
    account_type: "sales",
    account_type_bank: "",
    system_account: "",
    total_value: 234.0,
  },
  {
    account_category: "expense",
    account_code: "200",
    account_currency: "AUD",
    account_identifier: "e2bacdc6-2006-43c2-a5da-3c0e5f43b452",
    account_status: "ACTIVE",
    value_type: "credit",
    account_name: "Sales",
    account_type: "sales",
    account_type_bank: "",
    system_account: "",
    total_value: 333.0,
  },
  {
    account_category: "assets",
    account_code: "200",
    account_currency: "AUD",
    account_identifier: "e2bacdc6-2006-43c2-a5da-3c0e5f43b452",
    account_status: "ACTIVE",
    value_type: "credit",
    account_name: "Sales",
    account_type: "sales",
    account_type_bank: "",
    system_account: "",
    total_value: 124352.0,
  },
];
